cards = ('10_of_clubs',
         '10_of_diamonds',
         '10_of_hearts',
         '10_of_spades',
         '2_of_clubs',
         '2_of_diamonds',
         '2_of_hearts',
         '2_of_spades',
         '3_of_clubs',
         '3_of_diamonds',
         '3_of_hearts',
         '3_of_spades',
         '4_of_clubs',
         '4_of_diamonds',
         '4_of_hearts',
         '4_of_spades',
         '5_of_clubs',
         '5_of_diamonds',
         '5_of_hearts',
         '5_of_spades',
         '6_of_clubs',
         '6_of_diamonds',
         '6_of_hearts',
         '6_of_spades',
         '7_of_clubs',
         '7_of_diamonds',
         '7_of_hearts',
         '7_of_spades',
         '8_of_clubs',
         '8_of_diamonds',
         '8_of_hearts',
         '8_of_spades',
         '9_of_clubs',
         '9_of_diamonds',
         '9_of_hearts',
         '9_of_spades',
         'ace_of_clubs',
         'ace_of_diamonds',
         'ace_of_hearts',
         'ace_of_spades',
         'jack_of_clubs2',
         'jack_of_diamonds2',
         'jack_of_hearts2',
         'jack_of_spades2',
         'king_of_clubs2',
         'king_of_diamonds2',
         'king_of_hearts2',
         'king_of_spades2',
         'queen_of_clubs2',
         'queen_of_diamonds2',
         'queen_of_hearts2',
         'queen_of_spades2')

cards_dictionary = {'10_of_clubs': ('Playing_Cards/10_of_clubs.png', 10),
                    '10_of_diamonds': ('Playing_Cards/10_of_diamonds.png', 10),
                    '10_of_hearts': ('Playing_Cards/10_of_hearts.png', 10),
                    '10_of_spades': ('Playing_Cards/10_of_spades.png', 10),
                    '2_of_clubs': ('Playing_Cards/2_of_clubs.png', 2),
                    '2_of_diamonds': ('Playing_Cards/2_of_diamonds.png', 2),
                    '2_of_hearts': ('Playing_Cards/2_of_hearts.png', 2),
                    '2_of_spades': ('Playing_Cards/2_of_spades.png', 2),
                    '3_of_clubs': ('Playing_Cards/3_of_clubs.png', 3),
                    '3_of_diamonds': ('Playing_Cards/3_of_diamonds.png', 3),
                    '3_of_hearts': ('Playing_Cards/3_of_hearts.png', 3),
                    '3_of_spades': ('Playing_Cards/3_of_spades.png', 3),
                    '4_of_clubs': ('Playing_Cards/4_of_clubs.png', 4),
                    '4_of_diamonds': ('Playing_Cards/4_of_diamonds.png', 4),
                    '4_of_hearts': ('Playing_Cards/4_of_hearts.png', 4),
                    '4_of_spades': ('Playing_Cards/4_of_spades.png', 4),
                    '5_of_clubs': ('Playing_Cards/5_of_clubs.png', 5),
                    '5_of_diamonds': ('Playing_Cards/5_of_diamonds.png', 5),
                    '5_of_hearts': ('Playing_Cards/5_of_hearts.png', 5),
                    '5_of_spades': ('Playing_Cards/5_of_spades.png', 5),
                    '6_of_clubs': ('Playing_Cards/6_of_clubs.png', 6),
                    '6_of_diamonds': ('Playing_Cards/6_of_diamonds.png', 6),
                    '6_of_hearts': ('Playing_Cards/6_of_hearts.png', 6),
                    '6_of_spades': ('Playing_Cards/6_of_spades.png', 6),
                    '7_of_clubs': ('Playing_Cards/7_of_clubs.png', 7),
                    '7_of_diamonds': ('Playing_Cards/7_of_diamonds.png', 7),
                    '7_of_hearts': ('Playing_Cards/7_of_hearts.png', 7),
                    '7_of_spades': ('Playing_Cards/7_of_spades.png', 7),
                    '8_of_clubs': ('Playing_Cards/8_of_clubs.png', 8),
                    '8_of_diamonds': ('Playing_Cards/8_of_diamonds.png', 8),
                    '8_of_hearts': ('Playing_Cards/8_of_hearts.png', 8),
                    '8_of_spades': ('Playing_Cards/8_of_spades.png', 8),
                    '9_of_clubs': ('Playing_Cards/9_of_clubs.png', 9),
                    '9_of_diamonds': ('Playing_Cards/9_of_diamonds.png', 9),
                    '9_of_hearts': ('Playing_Cards/9_of_hearts.png', 9),
                    '9_of_spades': ('Playing_Cards/9_of_spades.png', 9),
                    'ace_of_clubs': ('Playing_Cards/ace_of_clubs.png', 10),
                    'ace_of_diamonds': ('Playing_Cards/ace_of_diamonds.png', 10),
                    'ace_of_hearts': ('Playing_Cards/ace_of_hearts.png', 10),
                    'ace_of_spades': ('Playing_Cards/ace_of_spades.png', 10),
                    'jack_of_clubs2': ('Playing_Cards/jack_of_clubs2.png', 10),
                    'jack_of_diamonds2': ('Playing_Cards/jack_of_diamonds2.png', 10),
                    'jack_of_hearts2': ('Playing_Cards/jack_of_hearts2.png', 10),
                    'jack_of_spades2': ('Playing_Cards/jack_of_spades2.png', 10),
                    'king_of_clubs2': ('Playing_Cards/king_of_clubs2.png', 10),
                    'king_of_diamonds2': ('Playing_Cards/king_of_diamonds2.png', 10),
                    'king_of_hearts2': ('Playing_Cards/king_of_hearts2.png', 10),
                    'king_of_spades2': ('Playing_Cards/king_of_spades2.png', 10),
                    'queen_of_clubs2': ('Playing_Cards/queen_of_clubs2.png', 10),
                    'queen_of_diamonds2': ('Playing_Cards/queen_of_diamonds2.png', 10),
                    'queen_of_hearts2': ('Playing_Cards/queen_of_hearts2.png', 10),
                    'queen_of_spades2': ('Playing_Cards/queen_of_spades2.png', 10)}
